language: ruby
cache: bundler
rvm:
    - 1.9.3
    - 2.1.1
install: bundle install

script: 'bundle exec rspec'
bundler_args: --without development

branches:
  only:
    - master
                 
notifications:
  email:
      - dirk.luesebrink@artcom.de
